title: Jackie Yang's Homepage
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Jackie Yang's Homepage. I'm a second year PhD student at Stanford University.
  You can find my projects, resume and more about me here.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jackie Yang # add your name
author-img: jackieyang.jpg # add your photo
about-author: I'm a second year PhD student at Stanford University.
  You can find my projects, resume and more about me here. # add description
author-resume: files/resume-2018-02-07.pdf
twitter: valkjsaaa # add your Twitter handle
github: valkjsaaa # add your Github handle
linkedin: jackie--yang # add your Linkedin handle
email: me@jackieyang.me # add your Email address
scholar: coVkhKMAAAAJ # Google Scholar

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jemoji

pagination:
  enabled: true
  per_page: 30
  permalink: "/page/:num/"
  sort_reverse: true

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
