source 'https://rubygems.org'
gem 'jekyll-last-modified-at'
gem "jekyll-assets"
gem 'jekyll'
# gem 'jekyll-coffeescript'
gem 'jekyll-sass-converter'
gem 'kramdown'
gem 'maruku'
gem 'rdiscount'
gem 'redcarpet'
gem 'RedCloth'
gem 'liquid'
gem 'pygments.rb'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-gist'
# gem 'jekyll-paginate'
# gem 'github-pages-health-check'
gem 'ruby'
gem 'html-pipeline'
gem 'sass'
gem 'safe_yaml'
# Enable Multiple Language!
# gem 'jekyll-polyglot'